In [1]:
#install Python package - Numpy
#pip install numpy

In [1]:
import numpy as np

In [3]:
myList=[1,2,3,4,5]
stringList=["apple","orange"]     

In [4]:
print(myList)
print(stringList)

[1, 2, 3, 4, 5]
['apple', 'orange']


In [5]:
myList

[1, 2, 3, 4, 5]

In [6]:
type(myList)

list

In [7]:
# dir(np)

In [8]:
#help(np)

In [9]:
arr = np.array(myList)

In [10]:
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
#shape of array
arr.shape

(5,)

In [12]:
arr.size

5

In [13]:
my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[9,7,6,8,9]
arr = np.array([my_list1,my_list2,my_list3])

In [14]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [15]:
type(arr)

numpy.ndarray

In [16]:
arr.shape

(3, 5)

In [17]:
arr.size

15

In [18]:
#Numpy array indexing
# Get the first from the following  array :
my_List1 = [1,2,3,4,5]
arr = np.array(my_List1)

In [19]:
arr

array([1, 2, 3, 4, 5])

In [20]:
print(arr[0])

1


In [21]:
print(arr[1])

2


In [22]:
print("The third element is :",arr[2],"and the fourth element is :",arr[3])

The third element is : 3 and the fourth element is : 4


In [23]:
# Acess 2D array
my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[9,7,6,8,9]
arr = np.array([my_list1,my_list2,my_list3])

In [24]:
arr


array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [25]:
arr[1,2]

4

In [26]:
print(arr[1,2])

4


In [27]:
arr[0]

array([1, 2, 3, 4, 5])

In [28]:
arr[0,2]

3

In [29]:
print("2nd element on 1st row",arr[0,1])

2nd element on 1st row 2


In [30]:
#Access the element on the 2nd rowb ,5th element
arr[1,4]

6

In [31]:
valarr = np.array([[1,2,3],[4,5,6]]) # create a 2D array
print("printint the variable  value",valarr,"\n")
print("printing the shape :",valarr.shape,"\n")
print("printing the size:",valarr.size,"\n")
#print first row first element
print("printing  the first row first element :",valarr[0,0],"\n")
# index 2nd row 3rd element
print("printing the second row third element :",valarr[1,2],"\n")

printint the variable  value [[1 2 3]
 [4 5 6]] 

printing the shape : (2, 3) 

printing the size: 6 

printing  the first row first element : 1 

printing the second row third element : 6 



In [32]:
newArr = np.array([[1,2,3,4,5],[6,7,8,9,10],[1,2,3,4,5],[11,12,13,14,15],[20,25,30,35,40]])

In [33]:
print("printint the variable  value",newArr,"\n")
print("printing the shape :",newArr.shape,"\n")
print("printing the size:",newArr.size,"\n")
#print first row first element
print("printing  the first row first element :",newArr[0,0],"\n")
# index 2nd row 3rd element
print("printing the second row third element :",newArr[1,2],"\n")

printint the variable  value [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [11 12 13 14 15]
 [20 25 30 35 40]] 

printing the shape : (5, 5) 

printing the size: 25 

printing  the first row first element : 1 

printing the second row third element : 8 



In [34]:
#negative indexing
myList = [1,2,3,4,5,6,7]
arr = np.array(myList)
# print(arr)

valarr = np.array([[1,2,3],[4,5,6]])
print(valarr)
a = mylist

[[1 2 3]
 [4 5 6]]


NameError: name 'mylist' is not defined

In [ ]:
valarr[1,-2]

In [ ]:
valarr[1,-1]

In [ ]:
# Numpy array slicing
mylist = np.array([1,2,3,4,5,6,7,8,9,10])
print(mylist)

In [ ]:
mylist[0:5]

In [ ]:
mylist[3:]

In [ ]:
mylist[:5]

In [ ]:
mylist[:-1] # print without last element

In [ ]:
mylist[-3:-1] # print from 8 to before last element

In [ ]:
mylist[-3:]

In [ ]:
#step(property name)
mylist[::2] # skip 2 values

In [ ]:
mylist[1::3]

In [ ]:
a[1::4] # a = mylist

In [ ]:
mylist[1::4]

In [3]:
# Slicing 2D array
my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[9,7,6,8,9]
arr = np.array([my_list1,my_list2,my_list3])

In [5]:
arr[1:,2:4]# first slicing of row after coma slicing of coloumns

array([[4, 5],
       [6, 8]])

In [4]:
arr[:2,1:4]

array([[2, 3, 4],
       [3, 4, 5]])

In [ ]:
#Arange function
np.arange(10) # create a array with 10 elements

In [2]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(5)

In [ ]:
np.arange(10,20,2) # similar to range function

In [ ]:
# Linspace
np.linspace(0,100) # create 0 to 100 normal distrubution following array 

In [ ]:
arr=np.array([1,23,4,5,6]) # Let Numpy choose datatype

print(arr.dtype) # print data type and storage space

In [6]:
arr=np.array(["apple","banana","orange","blueberry"])
print(arr.dtype)

<U9


In [35]:
arr = np.array([1,2,3,4,5],dtype=np.int64)
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


In [36]:
arr = np.array([1,2,3,4,5],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [ ]:
# Array math
x = np.array()