In [1]:
#install Python package - Numpy
#pip install numpy

In [1]:
import numpy as np

In [3]:
myList=[1,2,3,4,5]
stringList=["apple","orange"]     

In [4]:
print(myList)
print(stringList)

[1, 2, 3, 4, 5]
['apple', 'orange']


In [5]:
myList

[1, 2, 3, 4, 5]

In [6]:
type(myList)

list

In [7]:
# dir(np)

In [8]:
#help(np)

In [9]:
arr = np.array(myList)

In [10]:
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
#shape of array
arr.shape

(5,)

In [12]:
arr.size

5

In [13]:
my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[9,7,6,8,9]
arr = np.array([my_list1,my_list2,my_list3])

In [14]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [15]:
type(arr)

numpy.ndarray

In [16]:
arr.shape

(3, 5)

In [17]:
arr.size

15

In [18]:
#Numpy array indexing
# Get the first from the following  array :
my_List1 = [1,2,3,4,5]
arr = np.array(my_List1)

In [19]:
arr

array([1, 2, 3, 4, 5])

In [20]:
print(arr[0])

1


In [21]:
print(arr[1])

2


In [22]:
print("The third element is :",arr[2],"and the fourth element is :",arr[3])

The third element is : 3 and the fourth element is : 4


In [23]:
# Acess 2D array
my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[9,7,6,8,9]
arr = np.array([my_list1,my_list2,my_list3])

In [24]:
arr


array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [25]:
arr[1,2]

4

In [26]:
print(arr[1,2])

4


In [27]:
arr[0]

array([1, 2, 3, 4, 5])

In [28]:
arr[0,2]

3

In [29]:
print("2nd element on 1st row",arr[0,1])

2nd element on 1st row 2


In [30]:
#Access the element on the 2nd rowb ,5th element
arr[1,4]

6

In [31]:
valarr = np.array([[1,2,3],[4,5,6]]) # create a 2D array
print("printint the variable  value",valarr,"\n")
print("printing the shape :",valarr.shape,"\n")
print("printing the size:",valarr.size,"\n")
#print first row first element
print("printing  the first row first element :",valarr[0,0],"\n")
# index 2nd row 3rd element
print("printing the second row third element :",valarr[1,2],"\n")

printint the variable  value [[1 2 3]
 [4 5 6]] 

printing the shape : (2, 3) 

printing the size: 6 

printing  the first row first element : 1 

printing the second row third element : 6 



In [32]:
newArr = np.array([[1,2,3,4,5],[6,7,8,9,10],[1,2,3,4,5],[11,12,13,14,15],[20,25,30,35,40]])

In [33]:
print("printint the variable  value",newArr,"\n")
print("printing the shape :",newArr.shape,"\n")
print("printing the size:",newArr.size,"\n")
#print first row first element
print("printing  the first row first element :",newArr[0,0],"\n")
# index 2nd row 3rd element
print("printing the second row third element :",newArr[1,2],"\n")

printint the variable  value [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [11 12 13 14 15]
 [20 25 30 35 40]] 

printing the shape : (5, 5) 

printing the size: 25 

printing  the first row first element : 1 

printing the second row third element : 8 



In [34]:
#negative indexing
myList = [1,2,3,4,5,6,7]
arr = np.array(myList)
# print(arr)

valarr = np.array([[1,2,3],[4,5,6]])
print(valarr)
a = mylist

[[1 2 3]
 [4 5 6]]


NameError: name 'mylist' is not defined

In [ ]:
valarr[1,-2]

In [ ]:
valarr[1,-1]

In [2]:
# Numpy array slicing
mylist = np.array([1,2,3,4,5,6,7,8,9,10])
print(mylist)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
mylist[0:5]

array([1, 2, 3, 4, 5])

In [4]:
mylist[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [5]:
mylist[:5]

array([1, 2, 3, 4, 5])

In [6]:
mylist[:-1] # print without last element

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
mylist[-3:-1] # print from 8 to before last element

array([8, 9])

In [8]:
mylist[-3:]

array([ 8,  9, 10])

In [9]:
#step(property name)
mylist[::2] # skip 2 values

array([1, 3, 5, 7, 9])

In [10]:
mylist[1::3]

array([2, 5, 8])

In [11]:
a[1::4] # a = mylist

NameError: name 'a' is not defined

In [ ]:
mylist[1::4]

In [12]:
# Slicing 2D array
my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[9,7,6,8,9]
arr = np.array([my_list1,my_list2,my_list3])

In [13]:
arr[1:,2:4]# first slicing of row after coma slicing of coloumns

array([[4, 5],
       [6, 8]])

In [14]:
arr[:2,1:4]

array([[2, 3, 4],
       [3, 4, 5]])

In [15]:
#Arange function
np.arange(10) # create a array with 10 elements

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(10,20,2) # similar to range function

array([10, 12, 14, 16, 18])

In [19]:
# Linspace
np.linspace(0,100) # create 0 to 100 normal distrubution following array 

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [ ]:
arr=np.array([1,23,4,5,6]) # Let Numpy choose datatype

print(arr.dtype) # print data type and storage space

In [ ]:
arr=np.array(["apple","banana","orange","blueberry"])
print(arr.dtype)

In [ ]:
arr = np.array([1,2,3,4,5],dtype=np.int64)
print(arr)
print(arr.dtype)

In [ ]:
arr = np.array([1,2,3,4,5],dtype='S')
print(arr)
print(arr.dtype)

In [ ]:
# Array math
x = np.array([[1,2,],[3,4]],dtype=np.float64)
y = np.array([[5,6],[7,8]],dtype=np.float64)

In [ ]:
print(x)
print(y)

In [ ]:
#Adition
x+y

In [ ]:
#Substraction
x-y

In [ ]:
#Multiplication
x*y

In [ ]:
print(x*y)

In [ ]:
# Division
x/y


In [ ]:
x = np.array([[1,2],[3,4],[5,6]])
y = np.array([[5,6],[7,8]])

print(x.shape)
print(y.shape)
print(x+y) # bcuz of shape difference cant do any operation

In [ ]:
np.exp(x)

In [ ]:
np.log(x)

In [ ]:
np.cos(x)

In [ ]:
np.tan(x)

In [ ]:
#Floor , Ceil ,Round
x = np.array([[1.5,2.6],[3.1,4.9]],dtype=np.float64)

In [ ]:
x

In [ ]:
np.floor(x) #only base value

In [ ]:
np.ceil(x) # nxt value 

In [ ]:
np.round(x)# same as ceil but change only when it is nearer to change eg 4.9 will change to 5

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
z = np.array([[9,10],[11,12]], dtype=np.float64)

In [ ]:
x*y*z

In [ ]:
np.multiply(x,y,z) # only fist two matrixs are considered

In [ ]:
import numpy as np
x = np.array([[1,2],[3,4],[5,6]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

In [ ]:
v.dot(w) # multiply the rows and add total value


In [ ]:
np.dot(v,w)

In [ ]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

In [ ]:
np.sum(x,axis=0)

In [ ]:
np.sum(x,axis=1)

In [ ]:
axis=0/1 1:row 0:column
        

In [ ]:
x.T # Transpose

In [ ]:
# Make a copy, change the original array, and display both arrays:

arr = np.array([1, 2, 3, 4, 5])

In [ ]:
x = arr #(same as view function)

In [ ]:
print(x)

In [ ]:
arr[0] = 100

In [ ]:
print(arr)

In [ ]:
# Numpy array copy
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy() # x copied arr

In [ ]:
arr[0] = 100

In [ ]:
arr

In [ ]:
x # x wont change if we change the value of arr

In [ ]:
# Numpy array reshaping
arr = np.arange(1,13)

In [ ]:
arr

In [ ]:
arr.shape

In [ ]:
arr_new = arr.reshape(4,3) # dont exceed shape value (4 * 3 =12) shape=12 1D ~ 2D
print(arr_new)

In [ ]:
arr_new # 1D ~ 2D

In [ ]:
# Flattering the arrays
# 2D---->1D
arr_new.reshape(-1) 

In [ ]:
#iterating arrays
arr = np.arange(1,7).reshape(3,2)

In [ ]:
arr

In [ ]:
for i in arr:
    print(i)

In [ ]:
# Joining Numpy Arrays
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
np.concatenate((arr1,arr2))

In [ ]:
np.concatenate((arr1,arr2),axis=1)# if we axis we get row wise  array or column wise(default)

In [ ]:
arr

In [ ]:
arr1